[package]
name = "bootloader_limine"
version = "0.1.0"
edition = "2024"

[dependencies]
bootabi = { path = "../../bootabi" }
limine = { version = "0.5.0", default-features = false }

[lib]
crate-type = ["rlib"]
