[package]
name = "arch_x86_64"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
x86_64 = { version = "0.15", default-features = false }
bootabi = {path = "../../crates/bootabi"}
bootloader_limine = {path = "../../crates/bootloader/limine"}


