[package]
name = "arch_x86_64"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
crate-type = ["rlib"]

[dependencies]
x86_64 = { version = "0.15", default-features = false }
bootabi = {path = "../../crates/bootabi"}
hal = {path = "../../crates/hal"}

[build-dependencies]
cc = "1"
