[package]
name = "arch"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"
crate-type = ["rlib"]

[target.'cfg(target_arch = "x86_64")'.dependencies]
arch_x86_64 = { path = "x86_64" }

[target.'cfg(target_arch = "aarch64")'.dependencies]
arch_aarch64 = { path = "aarch64" }
